### PR TITLE
Fix #35: On demand transcription

### LINKED ISSUE #35: Transcribe audios only when requested
Hi! Congratulations, I really like this bot.

I have a functionality suggestion. It would be nice to add a new mode for transcribing audios only when a  group member cites the audio message with a command like `\transcribe`, for instance. In this way, the bot would only be activated when requested.

Thanks for your work!

### PR DESCRIPTION
**Pull request by The0xArchitect**
## Changes
- Added `/transcribe` command - to transcribe the `reply_to_message`
- Added the property `transcribeAllAudio` in the database as per [this suggestion](https://github.com/backmeupplz/voicy/pull/53#discussion_r781395505)
- Updated help message and `en.yaml` and `ru.yaml` to reflect the change
- Added `/transcribeAll` command to toggle the `transcribeAllAudio` property value.

Note:
All the guidelines from #53 have been followed. 

Hopefully fixes #35.

### CODE REVIEW

**Comment by backmeupplz** [comment]
@HeySreelal lgtm, did you test it manually?

**Comment by HeySreelal** [comment]
Good to hear that. Yes, I tested it manually. 

If you want to go a testing round I can start a test bot and share the bot details maybe?

**Comment by backmeupplz** [comment]
@HeySreelal nah, YOLO

**Comment by backmeupplz** [comment]
@HeySreelal can you fix `yarn lint`, please?

**Comment by HeySreelal** [comment]
Sure, let me check that in a moment...

**Comment by HeySreelal** [comment]
The `yarn lint` shows warnings on unused-vars. 
```
  67:16  warning  'sendToTelegramAdmin' is defined but never used  @typescript-eslint/no-unused-vars
  87:46  warning  'info' is assigned a value but never used        @typescript-eslint/no-unused-vars
```

I see that you've removed the error logging in this commit: https://github.com/backmeupplz/voicy/commit/548ae0c810f7b9355c27ff8b2ca5cab85dfb0eb4. 

Should I enable it back or just add some ignore flags?

**Comment by HeySreelal** [comment]
I just referenced all the unused identifiers inside the `report` method. Please let me know if you're actually looking to enable the logging or if this is fine :)

**Pull request merged**
